apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    is_default: true
    
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres://odoo:odoo@postgres:5432/integration
    database: integration
    user: odoo
    password: odoo
    jsonData:
      sslmode: disable
